/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSearchRouteImport } from './routes/dashboard.search'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMonitoringRouteImport } from './routes/dashboard.monitoring'
import { Route as DashboardApiDebugRouteImport } from './routes/dashboard.api-debug'
import { Route as CompanyIcoRouteImport } from './routes/company.$ico'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminImportsRouteImport } from './routes/admin.imports'
import { Route as AdminDatahubRouteImport } from './routes/admin.datahub'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminApiDebugRouteImport } from './routes/admin.api-debug'
import { Route as ApiPublicHooksDatahubWorkerRouteImport } from './routes/api/public/hooks/datahub-worker'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiDebugRoute = DashboardApiDebugRouteImport.update({
  id: '/api-debug',
  path: '/api-debug',
  getParentRoute: () => DashboardRoute,
} as any)
const CompanyIcoRoute = CompanyIcoRouteImport.update({
  id: '/company/$ico',
  path: '/company/$ico',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportsRoute = AdminImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatahubRoute = AdminDatahubRouteImport.update({
  id: '/datahub',
  path: '/datahub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiDebugRoute = AdminApiDebugRouteImport.update({
  id: '/api-debug',
  path: '/api-debug',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksDatahubWorkerRoute =
  ApiPublicHooksDatahubWorkerRouteImport.update({
    id: '/api/public/hooks/datahub-worker',
    path: '/api/public/hooks/datahub-worker',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/api-debug': typeof AdminApiDebugRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/datahub': typeof AdminDatahubRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/$ico': typeof CompanyIcoRoute
  '/dashboard/api-debug': typeof DashboardApiDebugRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/datahub-worker': typeof ApiPublicHooksDatahubWorkerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/api-debug': typeof AdminApiDebugRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/datahub': typeof AdminDatahubRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/$ico': typeof CompanyIcoRoute
  '/dashboard/api-debug': typeof DashboardApiDebugRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/hooks/datahub-worker': typeof ApiPublicHooksDatahubWorkerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin/api-debug': typeof AdminApiDebugRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/datahub': typeof AdminDatahubRoute
  '/admin/imports': typeof AdminImportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/$ico': typeof CompanyIcoRoute
  '/dashboard/api-debug': typeof DashboardApiDebugRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/datahub-worker': typeof ApiPublicHooksDatahubWorkerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/search'
    | '/admin/api-debug'
    | '/admin/companies'
    | '/admin/datahub'
    | '/admin/imports'
    | '/admin/settings'
    | '/admin/users'
    | '/company/$ico'
    | '/dashboard/api-debug'
    | '/dashboard/monitoring'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/search'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/hooks/datahub-worker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/admin/api-debug'
    | '/admin/companies'
    | '/admin/datahub'
    | '/admin/imports'
    | '/admin/settings'
    | '/admin/users'
    | '/company/$ico'
    | '/dashboard/api-debug'
    | '/dashboard/monitoring'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/search'
    | '/admin'
    | '/dashboard'
    | '/api/public/hooks/datahub-worker'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/search'
    | '/admin/api-debug'
    | '/admin/companies'
    | '/admin/datahub'
    | '/admin/imports'
    | '/admin/settings'
    | '/admin/users'
    | '/company/$ico'
    | '/dashboard/api-debug'
    | '/dashboard/monitoring'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/search'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/hooks/datahub-worker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  CompanyIcoRoute: typeof CompanyIcoRoute
  ApiPublicHooksDatahubWorkerRoute: typeof ApiPublicHooksDatahubWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring': {
      id: '/dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/dashboard/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-debug': {
      id: '/dashboard/api-debug'
      path: '/api-debug'
      fullPath: '/dashboard/api-debug'
      preLoaderRoute: typeof DashboardApiDebugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/company/$ico': {
      id: '/company/$ico'
      path: '/company/$ico'
      fullPath: '/company/$ico'
      preLoaderRoute: typeof CompanyIcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/imports': {
      id: '/admin/imports'
      path: '/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AdminImportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/datahub': {
      id: '/admin/datahub'
      path: '/datahub'
      fullPath: '/admin/datahub'
      preLoaderRoute: typeof AdminDatahubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-debug': {
      id: '/admin/api-debug'
      path: '/api-debug'
      fullPath: '/admin/api-debug'
      preLoaderRoute: typeof AdminApiDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/datahub-worker': {
      id: '/api/public/hooks/datahub-worker'
      path: '/api/public/hooks/datahub-worker'
      fullPath: '/api/public/hooks/datahub-worker'
      preLoaderRoute: typeof ApiPublicHooksDatahubWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApiDebugRoute: typeof AdminApiDebugRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDatahubRoute: typeof AdminDatahubRoute
  AdminImportsRoute: typeof AdminImportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiDebugRoute: AdminApiDebugRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDatahubRoute: AdminDatahubRoute,
  AdminImportsRoute: AdminImportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardApiDebugRoute: typeof DashboardApiDebugRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApiDebugRoute: DashboardApiDebugRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  CompanyIcoRoute: CompanyIcoRoute,
  ApiPublicHooksDatahubWorkerRoute: ApiPublicHooksDatahubWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
