// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwbexwehttmnsnohugtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3YmV4d2VodHRtbnNub2h1Z3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0MjY4MjQsImV4cCI6MjA5OTAwMjgyNH0.969qten3vGrSsapubT98xuch_-w8IeU_iBpry2NDZCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});